import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../services/api';

function BatchIngestion() {
  const [categoryUrl, setCategoryUrl] = useState('https://www.allrecipes.com/recipes/17562/dinner/');
  const [seedUrls, setSeedUrls] = useState('');
  const [maxRecipes, setMaxRecipes] = useState(50);
  const [jobId, setJobId] = useState(null);
  const queryClient = useQueryClient();

  // Inbox status query
  const { data: inboxStatus, refetch: refetchInbox } = useQuery({
    queryKey: ['inbox'],
    queryFn: () => api.getInboxStatus(),
    refetchInterval: 5000,  // Poll every 5 seconds
  });

  // Discover mutation
  const discoverMutation = useMutation({
    mutationFn: (data) => api.discoverAllRecipes(data.category_url, data.max_pages),
  });

  // Batch ingest mutation
  const batchMutation = useMutation({
    mutationFn: (data) => api.batchIngestAllRecipes(data),
    onSuccess: (data) => {
      setJobId(data.job_id);
    },
    onError: (error) => {
      alert(`Error: ${error.message}`);
    },
  });

  // Process inbox mutation
  const processInboxMutation = useMutation({
    mutationFn: () => api.processInbox('cooking'),
    onSuccess: (data) => {
      alert(`Processed ${data.processed} files from inbox!`);
      refetchInbox();
      queryClient.invalidateQueries({ queryKey: ['patterns'] });
      queryClient.invalidateQueries({ queryKey: ['domains'] });
    },
  });

  const handleDiscover = () => {
    discoverMutation.mutate({ category_url: categoryUrl, max_pages: 5 });
  };

  const handleBatchIngest = () => {
    const seeds = seedUrls.split('\n').map(u => u.trim()).filter(u => u);

    batchMutation.mutate({
      category_url: categoryUrl || null,
      seed_urls: seeds,
      max_recipes: parseInt(maxRecipes),
      domain: 'cooking',
    });
  };

  const handleProcessInbox = () => {
    processInboxMutation.mutate();
  };

  return (
    <div>
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900">Batch Ingestion</h2>
        <p className="text-gray-600 mt-1">Crawl AllRecipes and extract patterns from multiple recipes</p>
      </div>

      {/* AI Inbox Section */}
      <div className="mb-8 bg-purple-50 border border-purple-200 rounded-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-lg font-semibold text-purple-900">🤖 AI Recipe Inbox</h3>
            <p className="text-sm text-purple-700">
              Recipes generated by AI are saved to <code className="bg-purple-100 px-1 rounded">/development/eeframe/pattern-inbox/</code>
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => refetchInbox()}
              className="px-3 py-1 text-sm bg-purple-200 text-purple-800 rounded hover:bg-purple-300 transition"
            >
              Refresh
            </button>
            <button
              onClick={handleProcessInbox}
              disabled={processInboxMutation.isPending || (inboxStatus?.pending_files || 0) === 0}
              className="px-4 py-2 text-sm bg-purple-600 text-white rounded hover:bg-purple-700 disabled:bg-purple-300 transition"
            >
              {processInboxMutation.isPending ? 'Processing...' : `Process (${inboxStatus?.pending_files || 0})`}
            </button>
          </div>
        </div>

        {inboxStatus?.exists === false && (
          <p className="text-sm text-yellow-700">Inbox directory not found</p>
        )}

        {inboxStatus?.exists && inboxStatus?.files?.length > 0 && (
          <div className="mt-4">
            <p className="text-sm font-medium text-purple-900 mb-2">
              Pending Recipe Files:
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              {inboxStatus.files.map((file) => (
                <div key={file.name} className="text-xs bg-white p-2 rounded border">
                  <span className="font-mono">{file.name}</span>
                  <span className="text-gray-500 ml-2">({Math.round(file.size / 1024)} KB)</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {inboxStatus?.exists && inboxStatus?.files?.length === 0 && (
          <p className="text-sm text-gray-500">No pending files in inbox</p>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Configuration */}
        <div className="bg-white rounded-lg shadow p-6">
          <h3 className="text-lg font-semibold mb-4">Configuration</h3>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Category URL
              </label>
              <input
                type="url"
                value={categoryUrl}
                onChange={(e) => setCategoryUrl(e.target.value)}
                placeholder="https://www.allrecipes.com/recipes/17562/dinner/"
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
              />
              <p className="text-xs text-gray-500 mt-1">
                Leave empty to use seed URLs only
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Seed URLs (one per line, optional)
              </label>
              <textarea
                value={seedUrls}
                onChange={(e) => setSeedUrls(e.target.value)}
                placeholder="https://www.allrecipes.com/recipe/12345/..."
                rows={4}
                className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Max Recipes: {maxRecipes}
              </label>
              <input
                type="range"
                min="10"
                max="200"
                step="10"
                value={maxRecipes}
                onChange={(e) => setMaxRecipes(e.target.value)}
                className="w-full"
              />
            </div>

            <div className="flex gap-2">
              <button
                onClick={handleDiscover}
                disabled={discoverMutation.isPending || !categoryUrl}
                className="flex-1 px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:bg-gray-400 transition"
              >
                {discoverMutation.isPending ? 'Discovering...' : 'Discover Recipes'}
              </button>

              <button
                onClick={handleBatchIngest}
                disabled={batchMutation.isPending || (!categoryUrl && !seedUrls)}
                className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400 transition"
              >
                {batchMutation.isPending ? 'Starting...' : 'Start Batch Ingest'}
              </button>
            </div>
          </div>

          {/* Discovery Results */}
          {discoverMutation.data && (
            <div className="mt-6 p-4 bg-gray-50 rounded-lg">
              <h4 className="font-semibold mb-2">Discovery Results</h4>
              <p className="text-sm text-gray-600">
                Found {discoverMutation.data.recipes_found} recipe URLs
              </p>
              <p className="text-xs text-gray-500 mt-1">
                {discoverMutation.data.recipe_urls.slice(0, 3).map((u, i) => (
                  <span key={i} className="block truncate">{u}</span>
                ))}
                {discoverMutation.data.recipes_found > 3 && '...'}
              </p>
            </div>
          )}
        </div>

        {/* Job Status */}
        <div>
          {jobId && (
            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="font-semibold mb-4">Batch Job Status</h3>
              <JobMonitor jobId={jobId} />
            </div>
          )}

          {!jobId && (
            <div className="bg-white rounded-lg shadow p-6">
              <h3 className="font-semibold mb-4">How it works</h3>
              <ol className="list-decimal list-inside space-y-2 text-gray-600 text-sm">
                <li>Enter an AllRecipes category URL or specific recipe URLs</li>
                <li>Click "Discover" to see how many recipes are available</li>
                <li>Click "Start Batch Ingest" to begin extraction</li>
                <li>Patterns are extracted incrementally and saved</li>
                <li>Monitor progress in real-time</li>
              </ol>

              <div className="mt-4 p-3 bg-yellow-50 border border-yellow-200 rounded text-sm">
                <strong>Note:</strong> This will make many requests to AllRecipes.
                Use a delay between requests and be respectful.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function JobMonitor({ jobId }) {
  const { data: job } = useQuery({
    queryKey: ['job', jobId],
    queryFn: () => api.getJobStatus(jobId),
    refetchInterval: (data) => {
      if (data?.status === 'completed' || data?.status === 'failed') {
        return false;
      }
      return 1000;  // Poll every second when running
    },
  });

  if (!job) {
    return <div className="text-gray-500">Loading job status...</div>;
  }

  const statusColors = {
    queued: 'bg-yellow-100 text-yellow-800',
    processing: 'bg-blue-100 text-blue-800',
    completed: 'bg-green-100 text-green-800',
    failed: 'bg-red-100 text-red-800',
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <span className={`px-2 py-1 rounded text-xs ${statusColors[job.status] || 'bg-gray-100'}`}>
          {job.status.toUpperCase()}
        </span>
        <span className="text-sm text-gray-600">{job.progress}%</span>
      </div>

      {job.progress < 100 && job.status !== 'failed' && (
        <div className="w-full bg-gray-200 rounded-full h-2">
          <div
            className="bg-blue-600 h-2 rounded-full transition-all"
            style={{ width: `${job.progress}%` }}
          />
        </div>
      )}

      {/* Progress Details */}
      <div className="text-sm space-y-2 p-3 bg-gray-50 rounded">
        <div className="flex justify-between">
          <span className="text-gray-600">Status:</span>
          <span className="font-semibold">{job.status}</span>
        </div>

        <div className="flex justify-between">
          <span className="text-gray-600">Patterns extracted:</span>
          <span className="font-semibold">{job.patterns_extracted || 0}</span>
        </div>

        {job.current_recipe && (
          <div className="pt-2 border-t">
            <span className="text-gray-600 text-xs block mb-1">Currently processing:</span>
            <span className="text-xs text-blue-600 block truncate">{job.current_recipe}</span>
          </div>
        )}

        {job.max_recipes && job.status === 'processing' && (
          <div className="flex justify-between">
            <span className="text-gray-600">Progress:</span>
            <span className="font-semibold">{job.progress}% of {job.max_recipes} recipes</span>
          </div>
        )}
      </div>

      {/* Errors */}
      {job.errors?.length > 0 && (
        <div className="p-3 bg-red-50 border border-red-200 rounded">
          <p className="text-sm font-medium text-red-800">Errors ({job.errors.length}):</p>
          <div className="mt-2 max-h-32 overflow-y-auto">
            <ul className="text-xs text-red-700 space-y-1">
              {job.errors.slice(0, 10).map((err, i) => (
                <li key={i} className="truncate">{err}</li>
              ))}
              {job.errors.length > 10 && <li>...and {job.errors.length - 10} more</li>}
            </ul>
          </div>
        </div>
      )}

      {/* Done */}
      {job.status === 'completed' && (
        <div className="p-3 bg-green-50 border border-green-200 rounded">
          <p className="text-sm font-medium text-green-800">Batch completed!</p>
          <p className="text-xs text-green-700 mt-1">
            Extracted {job.patterns_extracted} patterns from {job.max_recipes || 'multiple'} recipes
          </p>
          <a href="/patterns" className="text-blue-600 hover:underline text-sm mt-2 inline-block">
            View patterns →
          </a>
        </div>
      )}
    </div>
  );
}

export default BatchIngestion;
